"""
Provides functionality to calculate finances.
"""

from typing import Callable


def sum_profit(text: str, func: Callable):
    """
    Calculates the total sum of float numbers generated by the provided function.

    Parameters:
        text (str): The input string containing numbers.
        func (Callable): A function that takes text and returns a generator of floats.

    Returns:
        float: The total sum of all extracted numbers.
    """
    total = sum(func(text))

    return total
